name: 'enterprise_dwh'
version: '1.0.0'
config-version: 2

profile: 'enterprise_dwh'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  enterprise_dwh:
    stage:
      +schema: warehouse

    marts:
      dimension:
        +schema: warehouse
        +materialized: table

      fact:
        +schema: warehouse
        +materialized: table

      sales:
        +schema: warehouse
        +materialized: table

      marketing:
        +schema: warehouse
        +materialized: table

snapshots:
  enterprise_dwh:
    +target_schema: warehouse
    +strategy: timestamp
    +updated_at: 'updated_at'
