retail_dwh:

  target: dev

  outputs:

    dev:

      type: snowflake

      account: dw03145.ap-south-1.aws

      user: JEETDAS0017

      password: Newzealandauck_2026

      role: ACCOUNTADMIN

      database: SNOWFLAKE_WH

      warehouse: COMPUTE_WH

      schema: STAGE

      threads: 4